# -*- coding: utf-8 -*-
"""Calculadora de Consumo Hídrico Residencial.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1NUMK4kNIF4-M9oYYhmzdV5bpx84VQc-l
"""

from IPython.display import clear_output
import time

ENCERRAR = 0
CALCULAR = 1

def mostrar_menu():
  print('Calculadora de Água')
  print('1 - Calcular')
  print('0 - Encerrar')
  return int(input('Informe a operação: '))

def calcular_conta():
  valor_total = float(input("Insira o valor total da conta de água: "))
  consumo_total = float(input("Insira o consumo total de água em m³: "))
  diferenca_consumo = float(input("Insira a diferença de consumo das casas 1 e 2, considerando os valores coletados no registro no mês anterior e atual: "))
  return valor_total / consumo_total * diferenca_consumo
  
def encerrar():
  clear_output()
  print('Encerrando...')
  time.sleep(3)
  clear_output()

def operacao_invalida():
  clear_output()
  print('Operação Inválida...')
  

operacao = mostrar_menu()

while(operacao != ENCERRAR):

  if(operacao == ENCERRAR):
    break
  elif operacao == CALCULAR:
    resultado = calcular_conta()
    print(f'\nO valor da conta de água da casa 2 é R$ {round(resultado,2)}\n')
  else:
    operacao_invalida()
  
  print('Deseja Continuar? ')
  operacao = int(input('Sim - 1 / Encerrar - 0: '))
  
  if(operacao == ENCERRAR):
    break;
  else:
    clear_output()
    operacao = mostrar_menu()

encerrar()